### ISSUE TITLE
HyperTerm

### ISSUE THREAD

**Issue by kennetpostigo** [sindresorhus/run-node#2]
Would this be useful in order to prevent HyperTerm from showing the node $PATH errors when using `nvm`.
I ask because this is a pending issue and I'm not sure if it would work for hyperterm:
https://github.com/zeit/hyperterm/issues/106

**Comment by sindresorhus** [comment]
Yup, answered in the thread: https://github.com/zeit/hyperterm/issues/106#issuecomment-233156685 :)
